---
- hosts: [all]
  gather_facts: False
  remote_user: root
  tasks:

    - name: Detect current username
      command: whoami
      register: local_username
      delegate_to: localhost
      run_once: True

    - name: Setup | authorized key upload
      authorized_key:
        user: "root"
        key: "{{ lookup('file', '/home/{{local_username.stdout}}/.ssh/id_rsa.pub') }}"
        path: '/root/.ssh/authorized_keys'
        exclusive: True
        manage_dir: no
      with_file:
        - "/home/{{ local_username.stdout }}/.ssh/known_hosts"

### This section is To update local known_hosts file (in case it changed) ###
- name: Store known hosts of 'all' the hosts in the inventory file
  hosts: localhost
  connection: local

  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['all'] }}"

  tasks:

  - name: For each host, scan for its ssh public key
    shell: "ssh-keyscan {{ item }},`dig +short {{ item }}`"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes

  - name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
    known_hosts:
      name: "{{ item.item }}"
      key: "{{ item.stdout }}"
      path: "{{ ssh_known_hosts_file }}"
    with_items: "{{ ssh_known_host_results.results }}"
