---
- hosts: all
  gather_facts: no
  tasks:
   - command: ping -c1 {{ inventory_hostname }}
     delegate_to: localhost
     register: ping_result
     ignore_errors: yes
   - group_by:
       key: reachable
     when: ping_result is success
   - group_by:
       key: unreachable
     when: ping_result is not success

   - block:
     - name: Setting facts for 'reachable' and 'unreachable' hosts
       set_fact:
         reachable: groups['reachable']|default(omit)
         unreachable: groups['unreachable']|default(omit)

     - name: Creating unreachable.txt file from template
       template:
         src: ../templates/unreachable.j2
         dest: ../unreachable.txt
       when: groups['unreachable'] is defined

     - name: Creating inventory.yml file out of only pingable hosts only
       template:
         src: ../templates/filtered_inv_template.j2
         dest: ../inventory.yml
     run_once: True
     delegate_to: localhost


### This section is To update local known_hosts file (in case it changed) ###
- name: Store known hosts of 'all' the hosts in the inventory file
  hosts: localhost
  connection: local

  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['reachable'] }}"

  tasks:

  - name: Detect current username
    command: whoami
    register: local_username

  - debug: var=local_username.stdout_lines|list|last

  - name: For each host, scan for its ssh public key
    shell: "ssh-keyscan {{ item }},`dig +short {{ item }}`"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes

  - name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
    known_hosts:
      name: "{{ item.item }}"
      key: "{{ item.stdout }}"
      path: "{{ ssh_known_hosts_file }}"
    with_items: "{{ ssh_known_host_results.results }}"

  - name: Set fact for public key and known hosts path if user IS root
    set_fact:
      pub_key_path: "{{ lookup('file', '/{{local_username.stdout}}/.ssh/id_rsa.pub') }}"
      known_hosts_path: "/{{ local_username.stdout }}/.ssh/known_hosts"
    when: local_username.stdout_lines|list|last == "root"
    run_once: True

  - name: Set fact for public key and known hosts path if user not root
    set_fact:
      pub_key_path: "{{ lookup('file', '/home/{{local_username.stdout}}/.ssh/id_rsa.pub') }}"
      known_hosts_path: "/home/{{ local_username.stdout }}/.ssh/known_hosts"
    when: local_username.stdout_lines|list|last != 'root'
    run_once: True



- hosts: [reachable]
  gather_facts: False
  remote_user: root
  tasks:

    - name: Setup | authorized key upload
      authorized_key:
        user: "root"
        key: "{{ hostvars['localhost']['pub_key_path'] }}"
        path: '/root/.ssh/authorized_keys'
        manage_dir: no
      with_file:
        - "{{ hostvars['localhost']['known_hosts_path'] }}"
